const host = "http://192.168.1.133:3050/"
//const host = "http://api.hypatiamat.com/"
module.exports.host = host
module.exports.hostAPI = host + "aplicacoes/"
module.exports.hostJogos = host + "jogos/"
module.exports.hostApps = host + "apps/"
module.exports.hostTrofeus = host + "trofeus/"
module.exports.hostCampeonatos = host + "campeonatos/"
module.exports.hostCromos = host + "cromos/"